height: 200
width: 50
max_length: 5
downsample_factor: 4


epochs: 10
batch_size: 32
split_ratio: 0.8
learning_rate: 0.001

csv_log_dir: ./logs/csv
checkpoint_dir: ./logs/checkpoints
csv_log_name: log.csv

csv : True
checkpoint : True
lr : True
